# Generated by Django 3.2.8 on 2021-11-02 22:08

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataCriacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('DataAlteracao', models.DateField(auto_now=True, verbose_name='Data de Alteração')),
                ('Ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('NomeCategoria', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataCriacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('DataAlteracao', models.DateField(auto_now=True, verbose_name='Data de Alteração')),
                ('Ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('NomeServico', models.CharField(max_length=35, verbose_name='Nome do Serviço')),
                ('DescricaoServico', models.CharField(max_length=255, verbose_name='Descrição')),
                ('ImageServico', stdimage.models.StdImageField(upload_to='servicos/images', verbose_name='Image')),
                ('SlugServico', models.SlugField(blank=True, editable=False, max_length=150, verbose_name='Slug')),
                ('Instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('Facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('FkCategoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
